# fly.toml app configuration file generated for my-father on 2023-04-27T14:22:32+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "my-father"
primary_region = "lhr"

[processes]
  web = "bundle exec puma -C config/puma.rb"

[[services]]
  internal_port = 3000
  processes = ["web"]
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[checks]
  [checks.alive]
    port = 3000
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"

[deploy]
  release_command = "bin/rails db:migrate"